### ISSUE TITLE
No scrollbar at https://kamailio.org/docs/tutorials/devel/kamailio-kemi-framework/modules/

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio-docs#22]
I click on https://kamailio.org/docs/tutorials/devel/kamailio-kemi-framework/modules/  or on https://kamailio.org/docs/tutorials/devel/kamailio-kemi-framework/core/  . I want to scroll the left box, where all function/modules are listed, by clicking on the scrollbar.  There is no scrollbar, so scrolling without a mouse-scroll-circle is utterly complicated.

**Comment by dilyanpalauzov** [comment]
Actually there is a scrollbar on the right of the window and with the up/down keys I can move up/down on both left and right window.  Once I click on a function name in the left half of the window, up/down arrow moves only the right side of the window.  The left side cannot be scrolled.

**Comment by henningw** [comment]
In my browser (Firefox) the scrolling with the mouse wheel works on the left page. There is no scroll bar, indeed.
The scrolling with the mouse don't work for you on the left side?

**Comment by dilyanpalauzov** [comment]
The point is that I have no mouse (currently).

**Comment by miconda** [comment]
The html version is generated with mkdocs from the repo at:

  - https://github.com/kamailio/kamailio-docs/tree/master/kamailio-kemi-framework

If you find any setting for mkdocs to add a scroll bar there, just make a pull request. Otherwise there is no much that can be done at this moment, you have to wait for mkdocs to add such option or contribute to that project.
